name: API Call Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-call:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up curl
      run: sudo apt-get install curl

    - name: Call External API
      env:
        API_KEY: ${{ secrets.API_KEY }}  # Reference to the secret API key
      run: |
        echo "Making API call..."
        curl -X GET "https://example.com/api/endpoint" \
          -H "Authorization: Bearer $API_KEY"
